apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      name: ktpv
    name: ktpv
    namespace: kubetests-prd
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "15Gi"
    volumeName: ktpv
kind: List
metadata: {}
