apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: test-runner
  selfLink: /apis/extensions/v1beta1/namespaces/test-runner/ingresses/jenkins
spec:
  rules:
  - host: jenkins.test-runner.prsn-dev.io
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 80
        path: /
